### ISSUE TITLE
Set the poster and preload attributes for videos hosted on OSF

### ISSUE THREAD

**Issue by allsey87** [brianjgeiger/markdown-it-video#40]
To save a lot of OSF bandwidth and to speed up the loading of content, I would strongly suggest the use of the `poster=path/to/poster.png` and `preload="none"` attributes of HTML video nodes. This would impact the video preview panel when browsing project files and also videos embedded in the wiki using the `@[osf](GUID)` method.

It would also be nice if eventually the poster images could be selected by the users when uploading video files, but I would say this is lower priority for now.

**Comment by Johnetordoff** [comment]
So I'm sorry I told you to move this only to then close it, but it turns out this will be more difficulty to implement then I thought and probably can't be done from markdown-it-video, it's more likely you'd actually need to change our [modular-file-render](https://github.com/CenterForOpenScience/modular-file-renderer) AKA MFR to actually accomplish. 

I sent a message to our dev who in charge of the MFR and he was positive about the change, but it would be difficult to work into are agile process anytime soon. I may personally just go put in a PR for this because I think it's a good suggestion, but it won't be merged or deployed within the next six months most likely. 

The OSF does not usually investigate or adopt feature requests unless they are very easy to QA test and give us a lot of utility. Yours was kind of on the edge of that so I looked into. Thanks for your suggestion, I'll try to credit you if this does get done. Or you could put in a PR into the MFR yourself and I'll make sure it gets a relatively speedy review. (Sometimes we ignore outside PRs, even good ones simply because we don't have the QA resources to ensure quality) Just remember to write tests.

**Comment by allsey87** [comment]
I was having a quick look at the source code and I agree that this looks like something that should be added in the MFR repository, specifically here:

https://github.com/CenterForOpenScience/modular-file-renderer/blob/master/mfr/extensions/video/templates/viewer.mako#L9

Or at least at a glance, you could add at this point the `preload="none"` attribute. The poster attribute is a bit more tricky, but I have some ideas. Perhaps we continue discussing on an issue in the MFR repo?
